clear all;
[t, y, u] = Sys2ODEsRK4('ODEdydtHW8_21a','ODEdudtHW8_21a',0,3,0.1,0,0)
subplot(3,1,1)
plot(t,y)
xlabel('Time (s)')
ylabel('Position (ft)')
subplot(3,1,2)
plot(t,u)
xlabel('Time (s)')
ylabel('Velocity (ft/s)')
Accel= ODEdudtHW8_21a(t,y,u)
subplot(3,1,3)
plot(t,Accel)
xlabel('Time (s)')
ylabel('Acceleration (ft/s^2)')